name: Bug report
description: File a bug against the `uuid` project
labels: ['bug']
title: '[BUG] <title>'

body:
  - type: checkboxes
    attributes:
      label: Before you begin...
      options:
        - label: I have searched the existing issues
          required: true
        - label: My issue title is descriptive and specific to the problem (i.e. search-engine friendly)
          required: true
        - label: I understand what an "MRE" is, and why providing one is important.  (If not, [read this](https://stackoverflow.com/help/minimal-reproducible-example))
          required: true

  - type: textarea
    attributes:
      label: MRE and Description
      description: '**IMPORTANT**: Failure to provide an MRE is likely to result in your issue being closed without comment.'
      render: bash
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: 'Output of `npx envinfo --system --browsers --npmPackages --binaries` goes here:'
    validations:
      required: false
