name: Close inactive issues
on:
  schedule:
    - cron: "45 2 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "Marking as stale due to 90 days with no activity."
          close-issue-message: "Closing issue due to 30 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
